### ISSUE TITLE
Support a component prop (or as prop) for ArchetypeEntities

### ISSUE THREAD

**Issue by verekia** [hmans/miniplex#145]
It would be nice to have a prop to render directly a component for each entity, instead of using the children:

```jsx
<ArchetypeEntities archetype="enemy" as={Enemy} />
```

Instead of:

```jsx
<ArchetypeEntities archetype="enemy">
  <Enemy />
</ArchetypeEntities>
```

**Comment by hmans** [comment]
This is going to be in 2.0 as discussed, so I'm closing this issue.
