### ISSUE TITLE
Dont throw an error when trying to remove component if it doesnt exist?

### ISSUE THREAD

**Issue by mikecann** [hmans/miniplex#187]
I usually am in favour of being more explicit with throwing errors when something is wrong but in this instance I wonder if it would be better just to carry on if the component doesnt exist rather than throwing an error?

https://github.com/hmans/miniplex/blob/main/packages/miniplex/src/World.ts#L207

Just makes things a little bit nicer to work with in user land (dont need to do a check before removing) and I cant see any instance where I really care that im trying to remove a non-existent component.

Please do let me know if im missing something tho.

**Comment by mikecann** [comment]
In the case of adding components however im not sure.. 

https://github.com/hmans/miniplex/blob/main/packages/miniplex/src/World.ts#L183

So maybe for sake of clarity its best to keep it?

**Comment by hmans** [comment]
You are right on the money with this, it has been one of my least favorite bits in Miniplex. After some user feedback that made it clear to me that the ECS-like strictness Miniplex was holding on to was causing various problems (from being cumbersome to, argh!, _making it really hard to make the damn thing work in React's StrictMode_), I started working on a major new version this week that I will be releasing as 2.0 soon. It'll be both more relaxed, eschewing some of the ECSisms for a more relaxed they're-just-objects approach, but also more flexible _and_ significantly faster, too.

I don't want to make major changes like this to 1.0 at this point, and would prefer to get 2.0 out as quickly as I can to have people use that instead. (If you're curious, I've been pushing [pre-release builds](https://github.com/hmans/miniplex/releases), but the documentation has not been updated yet.)

**Comment by hmans** [comment]
If you want to brief pre-documentation overview of what's coming in 2.0, please check out this issue: https://github.com/hmans/miniplex/issues/165

**Comment by mikecann** [comment]
Cool thanks, ill close this and comment over there then :)
