### ISSUE TITLE
Introduce safe mode vs. unsafe mode

### ISSUE THREAD

**Issue by hmans** [hmans/miniplex#55]
Miniplex currently (0.10.0) does a lot of sanity checks (like checking if an entity is actually managed by the world before mutating it). This is very useful while in development, but of course incurs a (slight) performance penalty. Let's introduce a toggle to allow the user to enable/disable these checks.

**Comment by madou** [comment]
Could you remove them for prod builds?

**Comment by hmans** [comment]
I'm closing this issue. 2.0 is getting close, and it's a lot more relaxed than 1.0, making this obsolete.
